### ISSUE TITLE
Cannot find any license information

### ISSUE THREAD

**Issue by PixelPartner** [liaScript/LiaScript#10]
I suggest to either use the Github WebUI or to add a LICENSE.txt/.md and clearify the licensing situation.

Whether you use a viral GPL or a less limiting BSD/MIT/Apache will decide about future developments, re-use of this gem.

**Comment by jhc-at-home** [comment]
Are you trying to suggest that using a copyleft license will kill LiaScript and using a permissive license will make it flourish? If not, then why the emotional language?

**Comment by PixelPartner** [comment]
Sorry, I now realize that it sounds emotionally loaded.
And yes, I've seen projects like this not been picked up with a GPL license.
I'm personally a big fan of GPL projects like Blender3D.
@andre-dietrich should just make it visible.

**Comment by andre-dietrich** [comment]
@PixelPartner @jhc-at-home  ... Just added a BSD 3 license, I think using the same license as the elm-compiler should be ok ;) ... I did not add a license so far, since I am absolutely not an expert on this topic, but LiaScript was always open-source, but without a license ... But you can suggest me license ;) ... Actually I would prefer the "NoEvil" license, I did some stuff in robotics and ROS, but now I am shocked that the military-sector is using all open-source algorithms from ROS for their purposes (of course not my buggy code)... Thus, it should not be too open, just kidding ...

**Comment by jhc-at-home** [comment]
@andre-dietrich This bug can be closed now I think? My personal preference would've been for a GPL copyleft license but BSD-3 clause is also perfectly fine for our purposes.

**Comment by andre-dietrich** [comment]
@jhc-at-home If you need some help on implementing a template for any specific javascript library, just create an issue... one of the next steps, is to create a documentation on how to define custom liascript extensions ...
