### ISSUE TITLE
Markdown images with spaces in description are not shown

### ISSUE THREAD

**Issue by aheil** [LiaScript/LiaScript#102]
Observed behavior: When using ![foo bar][(linkToImage) the image is not shown. Insted the text "![foo bar][(linkToImage)" is shwon.
Expected behavior: The image is rendered. 

I have not tested this with local resources using a relative path, however with remote images linked via https://... I have experienced this. 
The markdown rendered at GitHub worked pretty fine in contrast.

**Comment by SebastianZug** [comment]
Can you please provide or reference an exemplary LiaScript document? I would like to check this.

**Comment by aheil** [comment]
You will find an example that caused the issue at https://github.com/aheil/devops/blob/gh-pages/README.md.

However, while I tried to reproduce this issue, I realized, it was not the space, it was the tick. It can be found on the document above when searching for "Cover Test". 

![image](https://user-images.githubusercontent.com/509229/191824293-6b6d8b3c-072e-4750-90f9-7d08780e9e9e.png)

The image link causing the problem is the tick for a markdown code segment in the name O`Reilly.

I have copied the text/name - it looks like the text contained that particular apostrophe.

Therefore, the rendering seems to be right.

**Comment by andre-dietrich** [comment]
Thanks for the reported problem, we will have to take a look into the inline element parser ... As you have already mentioned, the problem is related to the backtick. However, you can make the backtick more explicit by using the following syntax.

``` markdown
![Cover des Buchs Phoenix vom Verlag O\`Reilly](https://oreilly.de/wp-content/uploads/2020/07/12508-scaled.jpg)
```
the escape will work in GitHub and LiaScript as well. Using the backslash will tell LiaScript that the content should not be interpreted as code...
