### ISSUE TITLE
[Feature Request] JSON input for faster loading

### ISSUE THREAD

**Issue by ian-knight-uofa** [LiaScript/LiaScript#104]
On slower devices, particularly mobile, the parsing step significantly contributes to loading time.
Since the parsed input can be easily exported to JSON using the liascript exporter, I would like to request a way to load a pre-parsed JSON file instead of a markdown file.
Possible approaches could be checking if the URL ends with a .json extension, contains some keyword, or even just attempting to parse the input file as JSON before parsing the markdown.
This could eventually be extended to caching the parsed version of the document.
I am happy to help implement this if approved.

**Comment by ian-knight-uofa** [comment]
Oop; it looks like this might already be implemented through indexDB. Sorry for the hassle!

**Comment by andre-dietrich** [comment]
Hi @ian-knight-uofa , the loading from the internal stored/cached version works only if you define a version >= 1.0.0 ... All other versions below are interpreted as development versions, which will force an entire reload/parsing. If you have defined a final version, such as 1.0.0 then the LiaScript interpreter will check this version, if the document that is loaded has the same version-number, it will load the already parsed content. Otherwise it will try to load the newer one. If you make updates to your document, this might then not be loaded if you do not increase the version-number (but only for users who already have loaded a previous version). Like in development, if you fix typos within the written content, then it is okay to increase the patch number. If you add content, quizzes, scripts, etc. to the end of your document, you can increase the minor number, and if you totally change the order of your course, or move around quizzes and script (things that preserve state), then you will have to update the major version. This will add a new entry/layer to the content stored in indexeddb.

This might sound a bit strange, but we use this also as an protection mechanism in order to protect the state of the user. Once a course has been loaded the states will be preserved as long as there is no major version change ... This was a solution for us to provide secure storage without the need for defining custom ids for quizzes, scripts, etc, which also might compromised due to copy and paste errors ...

I hope this makes sense ;-)

@SebastianZug what do you think of delivering content also as preprocessed json?

**Comment by ian-knight-uofa** [comment]
@andre-dietrich thanks for the clarification. 

Following this and after doing some more digging, it seems the extra parsing/loading time I'm seeing on the document I've been working on has something to do with the amount of LaTeX that needs to be rendered. Might look into this a bit further and report back; whether it's something to do with the LaTeX as written, or whether rendered latex could also be cached.

**Comment by andre-dietrich** [comment]
Hi @ian-knight-uofa ... do you already have a link or can share an example? I am curious about the LaTeX content ...
