### ISSUE TITLE
iframes embedded with ?? can not be styled

### ISSUE THREAD

**Issue by tilman-schieber** [LiaScript/LiaScript#182]
I am embedding an interactive website with `??`. This is rendered as an iframe with the typical ugly border. I am not able to remove this border.

I tried
1. `??[Addieralgorithmus](https://addieralgorithmus.replit.app/ "Additionsalgorithmus")<!--style = "border:none;"-->`
2.  a global stylesheet with `iframe {border: none !important;}`

in both cases no styles are applied and the ugly border still shows.

If i simply write an iframe tag in my liascript sourcecode everything works as intended.
This is a fine workaround but I would still prefer to use LiaScripts own ??-Syntax.

**Comment by andre-dietrich** [comment]
Hi, are you using the live-editor or a plugin ... this problem was addressed in the last update of LiaScript, thus styling oEmbeds should now work as expected. I tried your initial example, and on the LiveEditor it does work.

[Try it](https://liascript.github.io/LiveEditor/?/show/code/H4sIAAAAAAAAA1NWcMovSkktsuLisrePdkxJyUwtSsxJzy/KLMnILS2O1cgoKSkottLXT0SX0itKLcjJLNFLLCjQV1AC6SzJzM8rRlKhpGmjqKurUFxSmZNqq5QEsUchLz8v1VohIzUzPaPESsHY0rSgQklBV9cOAEpGejKKAAAA)

Could you try to update your editor-plugin or the live-server, and check if this fixed the problem for you too?
