### ISSUE TITLE
Option to disable row-headers in tables

### ISSUE THREAD

**Issue by tilman-schieber** [LiaScript/LiaScript#200]
# Summary
give an option to disable that the first column is considered a row-header

# Details
The first row gets always tagged with `role="row-header"` which leads to the column to be fixed when scrolling horizontally.
<img src="https://github.com/user-attachments/assets/dd87930d-a486-4b0f-b544-91d5e275b4ac" width="350">
similar to #196 ... there are many tables where this behaviour makes little sense.
providing an option to tables that does not tag the first column as row headers would be great

**Comment by andre-dietrich** [comment]
This was introduced, since we treated tables as data-sets ... maybe this can be removed, if the visualization is turned off.
However, I have seen that you have a line-break in one formula, you can define a initial comment within a cell to modify it.

``` markdown
<!-- data-type="none" -->
| <!--style="position: absolute"--> $A$ | $B$ | $A \implies B$ | $B \implies A$ | <!--style="min-width: 28rem"--> $(A \implies B) \land (B \implies A)$ |
|:-------------------------------------:|:---:|:--------------:|:--------------:|:---------------------------------------------------------------------:|
|   <!--style="position: unset"--> 0    |  0  |       0        |       0        |                                   0                                   |
|                   0                   |  1  |       1        |       0        |                                   0                                   |
|                   1                   |  0  |       0        |       1        |                                   0                                   |
|                   1                   |  1  |       1        |       1        |                                   1                                   |
```

The comments within the first column remove the stickyness from the cells, and comment in the last cell, prevents it from breaking ...

You can try this out [here](https://liascript.github.io/LiveEditor/?/show/code/H4sIAAAAAAAAA8VQQQuCMBi9+yte5iEPA+0Uo4Lq3D/osnDQYE5pkwj88W0aKGlqHeod9sHb+97e3hwHLiU5MiXyQjIjMgXPW88IQcIMI+ae842vMsV9ELL1Srg7be7S0nmmhdugYGedycJw32oQ7AKUCPbVucNJpLkUXKMm9g1R6Vp+qVDkJhJzoViurjyt3RZtixAnyVSCRdsmtD5eSckU0EpHX9XjxJegNhnQ31qhNDfVJyMrsV246dQO0XO+J4YQjUtQJ5uyaXVx8278p2RxDzfSWSfqT5MNdfZRsj7/brIHEAtjQ8wDAAA=)

---

Theoretically you could also put these HTML-comments into macros, to shorten the table, but this will then be visible on GitHub ....

**Comment by tilman-schieber** [comment]
I have now just added the following css to the head of the document and now I am happy with my truth tables.
No sticky columns and no sorting buttons...

```
.lia-table__sort {
  display: none
  }

.lia-table-responsive.has-thead-sticky.has-first-col-sticky .lia-table__head th:first-child {
  position: unset !important;
}

.lia-table-responsive.has-first-col-sticky .lia-table__data:first-child {
  position: unset !important;
}
```

**Comment by andre-dietrich** [comment]
If the data cannot be visualized or the user marks it with `<!-- data-type="none" -->` the first column will not be sticky anymore ...
