### ISSUE TITLE
two sided page 

### ISSUE THREAD

**Issue by fugohan** [liaScript/LiaScript#21]
I know it is possible to make a two sided page with HTML and Markdown but there must be an easier way. All I want is to have a picture on the left side and some Code samples on the right side. 

In my opinion there are many usecases in Powerpoint slides for this feature. But I dont know how a to implement this.

**Comment by andre-dietrich** [comment]
Hi, sure this is possible, you can put your two parts into two separate HTML div elements like this:

````markdown
<div>

<div style="float:left; width: 48%">

```javascript
var s = "JavaScript syntax highlighting";
alert(s);
```
<script>@input</script>

</div>

<div style="float:right; width: 48%">

```javascript
var s = "JavaScript syntax highlighting";
alert(s);
```
<script>@input</script>

</div>
````

You can use float to move the two parts onto different sides and also set their width ... The only thing I do not know at the moment is, that you can also use other styling features, so that your elements look are also responsive. 

Regards ...

**Comment by fugohan** [comment]
@andre-dietrich thank you for your fast help
