### ISSUE TITLE
Add GitHub Task-Support

### ISSUE THREAD

**Issue by andre-dietrich** [LiaScript/LiaScript#33]
GitHub flavored Markdown supports the definition of tasks:

``` markdown
- [ ] not yet done
- [X] done
```
which is rendered as follows:

- [ ] not yet done
- [X] done

It would be convenient, if LiaScript could support the same feature, which could be helpful to users to mark their progress, some properties, or something else. Furthermore, this should be combined with the LiaScript feature of attached scripts:

``` html
- [ ] not yet done
- [X] done
<script>
let task = @input // substituted by [false, true]
if (task[0] && task[1])
    alert("super")
else if (task[0] || task [1])
    alert("it is okay")
else
    alert("that is absolutely not sufficient")                             
</script>
```
Such attached scripts are not mandatory, but they allow to trigger a certain action, if the input value changes, which might be or might not be useful ;-)

**Comment by pwab** [comment]
Just tested it and it seems to work. Issue can be closed I guess.

#35 didn't close the issue automatically because the keyword (`closing`) was wrong. See here for reference: https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword

**Comment by andre-dietrich** [comment]
Tranks for hint .... I am closing :smile:
