### ISSUE TITLE
Inline HTML handled inconsistently

### ISSUE THREAD

**Issue by MaybeJustJames** [LiaScript/LiaScript#4]
The MD file here: https://raw.githubusercontent.com/jhc-at-home/scratch/master/README.md
contains:
```markdown
<details markdown="1">
<summary>Solution
</summary>

### A Header
1. Yes, add explanation here

**TODO**: add image
</details>
```

LiaScript renders:
```pre
<details markdown="1">
Solution 
```

Github renders:
<details markdown="1">
<summary>Solution
</summary>

### A Header
1. Yes, add explanation here

**TODO**: add image
</details>

**Comment by jhc-at-home** [comment]
After some investigation with @abotzki this is because `Lia.Parser.Parser.parse_titles` parses sections based on the regex in `Lia.Parser.Preprocessor.title_tag` or:
```regex
#+
```

Thus breaking the example above into these `sections` ready to parse:
```markdown
<details markdown="1">
<summary>Solution
</summary>

```
and
```markdown
1. Yes, add explanation here

**TODO**: add image
</details>
```

**Comment by andre-dietrich** [comment]
A header at the moment is always interpreted in relative to the main header, thus on a LiaScript-page the following sections will be presented as described within the (Level Info) ... The reason for this, at the moment the web-accessibility standard, which requires a page to start with a header/1 ... Thus SubTitle is rendered as h1, but only the styling is used to indicate that this is actually a h2 .... The other ones are interpreted relatively, so that the user jumps always to the beginning of slide ...

``` markdown
...

## SubTitle (Level 1)

<details markdown="1">
<summary>Solution</summary>

# A Header (Level 2)
1. Yes, add explanation here

### Another header (Level 4)

**TODO**: add image
</details>
```

I know, this is a bit counter-intuitive ....

**Comment by andre-dietrich** [comment]
Closing this, innerHTML should  now be rendered accordingly ...
