### ISSUE TITLE
Preview for Wikipedia links

### ISSUE THREAD

**Issue by axel-klinger** [LiaScript/LiaScript#82]
It would be great to have a mouseover preview for links to Wikipedia articles like it is done in Wikipedia, so that the user does not need to go to the website of Wikipedia if a brief preview is sufficiant for understanding. This would make reading more fluent.

**Comment by axel-klinger** [comment]
![Hover-Wikipedia](https://user-images.githubusercontent.com/1186309/150294110-f1be69ef-7753-43aa-9648-33ae571d28d6.png)

**Comment by andre-dietrich** [comment]
I thought this can be implemented faster, still not ready for production, but it seems to be working ... I think the best is, to disable this option by default, since it requires a lot of Browser effort to fetch the sites and extract the relevant information ... But I like the idea very much ...


![ezgif com-gif-maker(2)](https://user-images.githubusercontent.com/3089101/150543739-637399ad-d0a8-4369-9920-757aebf2a5e0.gif)

**Comment by andre-dietrich** [comment]
Ah, the mouse has not been recorded, but after an updated the tooltips should appear, but they have to be activated ... The first loading might take take some time. The later ones will be taken from a local cache and thus appear immediately ...

https://user-images.githubusercontent.com/3089101/150856139-63d8d7f9-bad7-4cff-8c69-c8a42164a4e5.mp4
